### ISSUE TITLE
MediaType (DTO) should not contains user or profil. Right ?

### ISSUE THREAD

**Issue by AnthoGdn** [M2GIL/travel-raml#39]

**Comment by AnthoGdn** [comment]
Or juste id of profile ?

**Comment by rdecamps** [comment]
I think it's not required for the front teams;
We can remove the owner on both responses and requests body ?

**Comment by yoannfleurydev** [comment]
The owner (UserDTO) is required in the media. Only the user that had upload the media can remove it from the files server and the databse.

**Comment by rdecamps** [comment]
Yes but for display only ? The owner is not required ?
Like in Trips

**Comment by yoannfleurydev** [comment]
If we are sure about that I can remove it from the spec. 

Can @totocap tell us if they want it or not ?
