### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by AbdelWebDev** [M2GIL/travel-raml#46]
/profiles
POST
Réponses:
PRECONDITION_FAILED 412
CREATED 201
Response.Data and Response.link (self)

/profiles/{id}
DELETE
NOT_FOUND 404
NO_CONTENT 204
Response.Data and Response.link (self)

/profiles/self
DELETE
NOT_FOUND 404
NO_CONTENT 204
Response.Data and Response.link (self)

/profiles
GET
NOT_FOUND 404 
OK 200
Response.Data and Response.link (self)

/profiles/{id}
GET   
NOT_FOUND 404 
OK 200
Response.Data and Response.link (self)

/profiles/self
GET   
NOT_FOUND 404 
OK 200
Response.Data and Response.link (self)

/profiles
PUT
Unprocessable Entity 422
NOT_FOUND 404 
PRECONDITION_FAILED 412 
OK 200
Response.Data and Response.link (self)

/profiles/self
PUT
UNPROCESSABLE_ENTITY 422
NOT_FOUND 404
PRECONDITION_FAILED 412
OK 200

**Comment by yoannfleurydev** [comment]
I'm on it

**Comment by yoannfleurydev** [comment]
Merge in PR 48
